/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetPartForm model module.
 * @module model/AssetPartForm
 * @version 0.2
 */
class AssetPartForm {
    /**
     * Constructs a new <code>AssetPartForm</code>.
     * Specification for an individual part of an ensemble asset. Used when purchasing specific parts of an ensemble rather than the complete set.
     * @alias module:model/AssetPartForm
     * @param assetId {Number} Unique identifier for the specific part asset. This is Hal Leonard's internal asset ID for the individual part.
     * @param orderLineId {Number} The vendor line number that identifies this specific part within the order. Used to distinguish multiple parts in the same order.
     */
    constructor(assetId, orderLineId) { 
        
        AssetPartForm.initialize(this, assetId, orderLineId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId, orderLineId) { 
        obj['asset_id'] = assetId;
        obj['order_line_id'] = orderLineId;
    }

    /**
     * Constructs a <code>AssetPartForm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetPartForm} obj Optional instance to populate.
     * @return {module:model/AssetPartForm} The populated <code>AssetPartForm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetPartForm();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'Number');
            }
            if (data.hasOwnProperty('order_line_id')) {
                obj['order_line_id'] = ApiClient.convertToType(data['order_line_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetPartForm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetPartForm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssetPartForm.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

AssetPartForm.RequiredProperties = ["asset_id", "order_line_id"];

/**
 * Unique identifier for the specific part asset. This is Hal Leonard's internal asset ID for the individual part.
 * @member {Number} asset_id
 */
AssetPartForm.prototype['asset_id'] = undefined;

/**
 * The vendor line number that identifies this specific part within the order. Used to distinguish multiple parts in the same order.
 * @member {Number} order_line_id
 */
AssetPartForm.prototype['order_line_id'] = undefined;






export default AssetPartForm;

