/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetItem from './AssetItem';

/**
 * The AssetsListResponse model module.
 * @module model/AssetsListResponse
 * @version 0.2
 */
class AssetsListResponse {
    /**
     * Constructs a new <code>AssetsListResponse</code>.
     * AssetsListResponse
     * @alias module:model/AssetsListResponse
     * @param assets {Array.<module:model/AssetItem>} Array of asset objects containing complete metadata
     * @param lastId {Number} The ID of the last asset in the current page. Used as the last_id parameter for retrieving the next page.
     * @param nextPage {String} URL to retrieve the next page of assets. Null if there are no more assets.
     */
    constructor(assets, lastId, nextPage) { 
        
        AssetsListResponse.initialize(this, assets, lastId, nextPage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assets, lastId, nextPage) { 
        obj['assets'] = assets;
        obj['last_id'] = lastId;
        obj['next_page'] = nextPage;
    }

    /**
     * Constructs a <code>AssetsListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsListResponse} obj Optional instance to populate.
     * @return {module:model/AssetsListResponse} The populated <code>AssetsListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsListResponse();

            if (data.hasOwnProperty('assets')) {
                obj['assets'] = ApiClient.convertToType(data['assets'], [AssetItem]);
            }
            if (data.hasOwnProperty('last_id')) {
                obj['last_id'] = ApiClient.convertToType(data['last_id'], 'Number');
            }
            if (data.hasOwnProperty('next_page')) {
                obj['next_page'] = ApiClient.convertToType(data['next_page'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsListResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AssetsListResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['assets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['assets'])) {
                throw new Error("Expected the field `assets` to be an array in the JSON data but got " + data['assets']);
            }
            // validate the optional field `assets` (array)
            for (const item of data['assets']) {
                AssetItem.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['next_page'] && !(typeof data['next_page'] === 'string' || data['next_page'] instanceof String)) {
            throw new Error("Expected the field `next_page` to be a primitive type in the JSON string but got " + data['next_page']);
        }

        return true;
    }


}

AssetsListResponse.RequiredProperties = ["assets", "last_id", "next_page"];

/**
 * Array of asset objects containing complete metadata
 * @member {Array.<module:model/AssetItem>} assets
 */
AssetsListResponse.prototype['assets'] = undefined;

/**
 * The ID of the last asset in the current page. Used as the last_id parameter for retrieving the next page.
 * @member {Number} last_id
 */
AssetsListResponse.prototype['last_id'] = undefined;

/**
 * URL to retrieve the next page of assets. Null if there are no more assets.
 * @member {String} next_page
 */
AssetsListResponse.prototype['next_page'] = undefined;






export default AssetsListResponse;

