/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContributorItem from './ContributorItem';
import ImageItem from './ImageItem';
import InstrumentItem from './InstrumentItem';
import PackageItem from './PackageItem';
import PriceItem from './PriceItem';
import RelatedGoodItem from './RelatedGoodItem';
import RenderingItem from './RenderingItem';
import UsergenItem from './UsergenItem';

/**
 * The AssetItem model module.
 * @module model/AssetItem
 * @version 0.2
 */
class AssetItem {
    /**
     * Constructs a new <code>AssetItem</code>.
     * Digital asset with complete metadata. Represents a digital product available for purchase, including sheet music, recordings, and other media.
     * @alias module:model/AssetItem
     */
    constructor() { 
        
        AssetItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetItem} obj Optional instance to populate.
     * @return {module:model/AssetItem} The populated <code>AssetItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetItem();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'Number');
            }
            if (data.hasOwnProperty('format_short_name')) {
                obj['format_short_name'] = ApiClient.convertToType(data['format_short_name'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('page_count')) {
                obj['page_count'] = ApiClient.convertToType(data['page_count'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('song_number')) {
                obj['song_number'] = ApiClient.convertToType(data['song_number'], 'Number');
            }
            if (data.hasOwnProperty('public_domain')) {
                obj['public_domain'] = ApiClient.convertToType(data['public_domain'], 'Boolean');
            }
            if (data.hasOwnProperty('external_ref')) {
                obj['external_ref'] = ApiClient.convertToType(data['external_ref'], 'String');
            }
            if (data.hasOwnProperty('external_ref_id')) {
                obj['external_ref_id'] = ApiClient.convertToType(data['external_ref_id'], 'Number');
            }
            if (data.hasOwnProperty('voicing')) {
                obj['voicing'] = ApiClient.convertToType(data['voicing'], 'String');
            }
            if (data.hasOwnProperty('performance_time')) {
                obj['performance_time'] = ApiClient.convertToType(data['performance_time'], 'Number');
            }
            if (data.hasOwnProperty('difficulty_level_low')) {
                obj['difficulty_level_low'] = ApiClient.convertToType(data['difficulty_level_low'], 'Number');
            }
            if (data.hasOwnProperty('difficulty_level_high')) {
                obj['difficulty_level_high'] = ApiClient.convertToType(data['difficulty_level_high'], 'Number');
            }
            if (data.hasOwnProperty('min_qty')) {
                obj['min_qty'] = ApiClient.convertToType(data['min_qty'], 'Number');
            }
            if (data.hasOwnProperty('tempo')) {
                obj['tempo'] = ApiClient.convertToType(data['tempo'], 'Number');
            }
            if (data.hasOwnProperty('world')) {
                obj['world'] = ApiClient.convertToType(data['world'], 'Boolean');
            }
            if (data.hasOwnProperty('retail_price')) {
                obj['retail_price'] = ApiClient.convertToType(data['retail_price'], 'Number');
            }
            if (data.hasOwnProperty('smd_id')) {
                obj['smd_id'] = ApiClient.convertToType(data['smd_id'], 'String');
            }
            if (data.hasOwnProperty('asset_type')) {
                obj['asset_type'] = ApiClient.convertToType(data['asset_type'], 'String');
            }
            if (data.hasOwnProperty('explicit')) {
                obj['explicit'] = ApiClient.convertToType(data['explicit'], 'Boolean');
            }
            if (data.hasOwnProperty('partable')) {
                obj['partable'] = ApiClient.convertToType(data['partable'], 'Boolean');
            }
            if (data.hasOwnProperty('countries')) {
                obj['countries'] = ApiClient.convertToType(data['countries'], ['String']);
            }
            if (data.hasOwnProperty('instruments')) {
                obj['instruments'] = ApiClient.convertToType(data['instruments'], [InstrumentItem]);
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], ['String']);
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [ImageItem]);
            }
            if (data.hasOwnProperty('contributors')) {
                obj['contributors'] = ApiClient.convertToType(data['contributors'], [ContributorItem]);
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ApiClient.convertToType(data['keywords'], ['String']);
            }
            if (data.hasOwnProperty('related_goods')) {
                obj['related_goods'] = ApiClient.convertToType(data['related_goods'], [RelatedGoodItem]);
            }
            if (data.hasOwnProperty('renderings')) {
                obj['renderings'] = ApiClient.convertToType(data['renderings'], [RenderingItem]);
            }
            if (data.hasOwnProperty('series')) {
                obj['series'] = ApiClient.convertToType(data['series'], ['String']);
            }
            if (data.hasOwnProperty('skills')) {
                obj['skills'] = ApiClient.convertToType(data['skills'], ['String']);
            }
            if (data.hasOwnProperty('usergens')) {
                obj['usergens'] = ApiClient.convertToType(data['usergens'], [UsergenItem]);
            }
            if (data.hasOwnProperty('prices')) {
                obj['prices'] = ApiClient.convertToType(data['prices'], [PriceItem]);
            }
            if (data.hasOwnProperty('packages')) {
                obj['packages'] = ApiClient.convertToType(data['packages'], [PackageItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['format_short_name'] && !(typeof data['format_short_name'] === 'string' || data['format_short_name'] instanceof String)) {
            throw new Error("Expected the field `format_short_name` to be a primitive type in the JSON string but got " + data['format_short_name']);
        }
        // ensure the json data is a string
        if (data['format'] && !(typeof data['format'] === 'string' || data['format'] instanceof String)) {
            throw new Error("Expected the field `format` to be a primitive type in the JSON string but got " + data['format']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['external_ref'] && !(typeof data['external_ref'] === 'string' || data['external_ref'] instanceof String)) {
            throw new Error("Expected the field `external_ref` to be a primitive type in the JSON string but got " + data['external_ref']);
        }
        // ensure the json data is a string
        if (data['voicing'] && !(typeof data['voicing'] === 'string' || data['voicing'] instanceof String)) {
            throw new Error("Expected the field `voicing` to be a primitive type in the JSON string but got " + data['voicing']);
        }
        // ensure the json data is a string
        if (data['smd_id'] && !(typeof data['smd_id'] === 'string' || data['smd_id'] instanceof String)) {
            throw new Error("Expected the field `smd_id` to be a primitive type in the JSON string but got " + data['smd_id']);
        }
        // ensure the json data is a string
        if (data['asset_type'] && !(typeof data['asset_type'] === 'string' || data['asset_type'] instanceof String)) {
            throw new Error("Expected the field `asset_type` to be a primitive type in the JSON string but got " + data['asset_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['countries'])) {
            throw new Error("Expected the field `countries` to be an array in the JSON data but got " + data['countries']);
        }
        if (data['instruments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['instruments'])) {
                throw new Error("Expected the field `instruments` to be an array in the JSON data but got " + data['instruments']);
            }
            // validate the optional field `instruments` (array)
            for (const item of data['instruments']) {
                InstrumentItem.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['categories'])) {
            throw new Error("Expected the field `categories` to be an array in the JSON data but got " + data['categories']);
        }
        if (data['images']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['images'])) {
                throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
            }
            // validate the optional field `images` (array)
            for (const item of data['images']) {
                ImageItem.validateJSON(item);
            };
        }
        if (data['contributors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['contributors'])) {
                throw new Error("Expected the field `contributors` to be an array in the JSON data but got " + data['contributors']);
            }
            // validate the optional field `contributors` (array)
            for (const item of data['contributors']) {
                ContributorItem.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['keywords'])) {
            throw new Error("Expected the field `keywords` to be an array in the JSON data but got " + data['keywords']);
        }
        if (data['related_goods']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['related_goods'])) {
                throw new Error("Expected the field `related_goods` to be an array in the JSON data but got " + data['related_goods']);
            }
            // validate the optional field `related_goods` (array)
            for (const item of data['related_goods']) {
                RelatedGoodItem.validateJSON(item);
            };
        }
        if (data['renderings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['renderings'])) {
                throw new Error("Expected the field `renderings` to be an array in the JSON data but got " + data['renderings']);
            }
            // validate the optional field `renderings` (array)
            for (const item of data['renderings']) {
                RenderingItem.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['series'])) {
            throw new Error("Expected the field `series` to be an array in the JSON data but got " + data['series']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['skills'])) {
            throw new Error("Expected the field `skills` to be an array in the JSON data but got " + data['skills']);
        }
        if (data['usergens']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['usergens'])) {
                throw new Error("Expected the field `usergens` to be an array in the JSON data but got " + data['usergens']);
            }
            // validate the optional field `usergens` (array)
            for (const item of data['usergens']) {
                UsergenItem.validateJSON(item);
            };
        }
        if (data['prices']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['prices'])) {
                throw new Error("Expected the field `prices` to be an array in the JSON data but got " + data['prices']);
            }
            // validate the optional field `prices` (array)
            for (const item of data['prices']) {
                PriceItem.validateJSON(item);
            };
        }
        if (data['packages']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['packages'])) {
                throw new Error("Expected the field `packages` to be an array in the JSON data but got " + data['packages']);
            }
            // validate the optional field `packages` (array)
            for (const item of data['packages']) {
                PackageItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Unique identifier for the asset. This is Hal Leonard's internal identifier for the digital product.
 * @member {Number} asset_id
 */
AssetItem.prototype['asset_id'] = undefined;

/**
 * Short name of the asset format (e.g., PVG for Piano/Vocal/Guitar, SSA for Soprano/Soprano/Alto).
 * @member {String} format_short_name
 */
AssetItem.prototype['format_short_name'] = undefined;

/**
 * Full name of the asset format (e.g., Piano/Vocal/Guitar, Soprano/Soprano/Alto).
 * @member {String} format
 */
AssetItem.prototype['format'] = undefined;

/**
 * The number of pages in the sheet music or document.
 * @member {Number} page_count
 */
AssetItem.prototype['page_count'] = undefined;

/**
 * Title of the asset (song or composition name).
 * @member {String} title
 */
AssetItem.prototype['title'] = undefined;

/**
 * Detailed description of the asset, including background information, arrangement details, and other relevant content.
 * @member {String} description
 */
AssetItem.prototype['description'] = undefined;

/**
 * Hal Leonard's internal song identifier. This is a unique number assigned to each musical composition.
 * @member {Number} song_number
 */
AssetItem.prototype['song_number'] = undefined;

/**
 * Indicates whether the song represented by this asset exists in the public domain.
 * @member {Boolean} public_domain
 */
AssetItem.prototype['public_domain'] = undefined;

/**
 * Identifier of the company providing the asset. This field identifies the external source or provider of the asset.
 * @member {String} external_ref
 */
AssetItem.prototype['external_ref'] = undefined;

/**
 * Numeric identifier of the company providing the asset.
 * @member {Number} external_ref_id
 */
AssetItem.prototype['external_ref_id'] = undefined;

/**
 * Voicing configuration for choral format assets (e.g., SATB for Soprano/Alto/Tenor/Bass, SSA for Soprano/Soprano/Alto).
 * @member {String} voicing
 */
AssetItem.prototype['voicing'] = undefined;

/**
 * Performance duration of the asset in seconds.
 * @member {Number} performance_time
 */
AssetItem.prototype['performance_time'] = undefined;

/**
 * Lower bound of difficulty level on a scale (typically 1-5 or 1-10).
 * @member {Number} difficulty_level_low
 */
AssetItem.prototype['difficulty_level_low'] = undefined;

/**
 * Upper bound of difficulty level on a scale (typically 1-5 or 1-10).
 * @member {Number} difficulty_level_high
 */
AssetItem.prototype['difficulty_level_high'] = undefined;

/**
 * Minimum allowed purchase quantity, typically enforced on choral format assets to ensure complete sets are purchased.
 * @member {Number} min_qty
 */
AssetItem.prototype['min_qty'] = undefined;

/**
 * Tempo of the musical piece in beats per minute (BPM).
 * @member {Number} tempo
 */
AssetItem.prototype['tempo'] = undefined;

/**
 * Indicates if the asset can be sold in all countries (true) or has geographic restrictions (false).
 * @member {Boolean} world
 */
AssetItem.prototype['world'] = undefined;

/**
 * Hal Leonard's suggested retail price for the asset in the vendor's currency.
 * @member {Number} retail_price
 */
AssetItem.prototype['retail_price'] = undefined;

/**
 * SMD (Sheet Music Direct) identifier for the asset.
 * @member {String} smd_id
 */
AssetItem.prototype['smd_id'] = undefined;

/**
 * Type classification of the asset (e.g., FOLIO for folio editions, CHMBK for chord books, PCK for packs).
 * @member {String} asset_type
 */
AssetItem.prototype['asset_type'] = undefined;

/**
 * Indicator that denotes whether an asset contains graphic material such as profanity in lyrics.
 * @member {Boolean} explicit
 */
AssetItem.prototype['explicit'] = undefined;

/**
 * Indicator that denotes whether an ensemble's parts may be sold individually.
 * @member {Boolean} partable
 */
AssetItem.prototype['partable'] = undefined;

/**
 * List of ISO 3166-1 alpha-2 country codes where the asset is available for sale.
 * @member {Array.<String>} countries
 */
AssetItem.prototype['countries'] = undefined;

/**
 * List of instruments associated with the asset.
 * @member {Array.<module:model/InstrumentItem>} instruments
 */
AssetItem.prototype['instruments'] = undefined;

/**
 * List of categories that classify the asset (e.g., Pop, Rock, Jazz).
 * @member {Array.<String>} categories
 */
AssetItem.prototype['categories'] = undefined;

/**
 * List of images associated with the asset (cover art, sample pages, etc.).
 * @member {Array.<module:model/ImageItem>} images
 */
AssetItem.prototype['images'] = undefined;

/**
 * List of contributors (composers, arrangers, editors, etc.) associated with the asset.
 * @member {Array.<module:model/ContributorItem>} contributors
 */
AssetItem.prototype['contributors'] = undefined;

/**
 * List of keywords associated with the asset for search and discovery.
 * @member {Array.<String>} keywords
 */
AssetItem.prototype['keywords'] = undefined;

/**
 * List of related goods (physical products, digital bundles, etc.) associated with the asset.
 * @member {Array.<module:model/RelatedGoodItem>} related_goods
 */
AssetItem.prototype['related_goods'] = undefined;

/**
 * List of available renderings (formats) for the asset (e.g., PDF, Scorch, MusicXML).
 * @member {Array.<module:model/RenderingItem>} renderings
 */
AssetItem.prototype['renderings'] = undefined;

/**
 * List of series that the asset belongs to (e.g., Best Sellers, Top Hits collections).
 * @member {Array.<String>} series
 */
AssetItem.prototype['series'] = undefined;

/**
 * List of skill levels or educational classifications associated with the asset.
 * @member {Array.<String>} skills
 */
AssetItem.prototype['skills'] = undefined;

/**
 * List of user-generated content or customization options associated with the asset.
 * @member {Array.<module:model/UsergenItem>} usergens
 */
AssetItem.prototype['usergens'] = undefined;

/**
 * List of pricing options for the asset in different currencies or for different customer segments.
 * @member {Array.<module:model/PriceItem>} prices
 */
AssetItem.prototype['prices'] = undefined;

/**
 * List of package deals or bundles that include this asset.
 * @member {Array.<module:model/PackageItem>} packages
 */
AssetItem.prototype['packages'] = undefined;






export default AssetItem;

