/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContributorItem model module.
 * @module model/ContributorItem
 * @version 0.2
 */
class ContributorItem {
    /**
     * Constructs a new <code>ContributorItem</code>.
     * Contributor information including composers, arrangers, editors, and other personnel associated with an asset.
     * @alias module:model/ContributorItem
     */
    constructor() { 
        
        ContributorItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContributorItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContributorItem} obj Optional instance to populate.
     * @return {module:model/ContributorItem} The populated <code>ContributorItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContributorItem();

            if (data.hasOwnProperty('is_primary')) {
                obj['is_primary'] = ApiClient.convertToType(data['is_primary'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('mbid')) {
                obj['mbid'] = ApiClient.convertToType(data['mbid'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContributorItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContributorItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['mbid'] && !(typeof data['mbid'] === 'string' || data['mbid'] instanceof String)) {
            throw new Error("Expected the field `mbid` to be a primitive type in the JSON string but got " + data['mbid']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }

        return true;
    }


}



/**
 * Indicates if this is the primary contributor for the asset.
 * @member {Boolean} is_primary
 */
ContributorItem.prototype['is_primary'] = undefined;

/**
 * Name of the contributor.
 * @member {String} name
 */
ContributorItem.prototype['name'] = undefined;

/**
 * MusicBrainz ID for the contributor.
 * @member {String} mbid
 */
ContributorItem.prototype['mbid'] = undefined;

/**
 * Role of the contributor (e.g., Composer, Arranger, Editor).
 * @member {String} role
 */
ContributorItem.prototype['role'] = undefined;






export default ContributorItem;

