/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HealthItem model module.
 * @module model/HealthItem
 * @version 0.2
 */
class HealthItem {
    /**
     * Constructs a new <code>HealthItem</code>.
     * Health check result for a system component. Indicates whether a specific system component is functioning properly.
     * @alias module:model/HealthItem
     * @param name {String} Name of the system component being checked (e.g., database, cache, external service).
     * @param health {Boolean} Health status of the component. True indicates the component is functioning properly, false indicates a problem.
     */
    constructor(name, health) { 
        
        HealthItem.initialize(this, name, health);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, health) { 
        obj['name'] = name;
        obj['health'] = health;
    }

    /**
     * Constructs a <code>HealthItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HealthItem} obj Optional instance to populate.
     * @return {module:model/HealthItem} The populated <code>HealthItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HealthItem();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('health')) {
                obj['health'] = ApiClient.convertToType(data['health'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HealthItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HealthItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HealthItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

HealthItem.RequiredProperties = ["name", "health"];

/**
 * Name of the system component being checked (e.g., database, cache, external service).
 * @member {String} name
 */
HealthItem.prototype['name'] = undefined;

/**
 * Health status of the component. True indicates the component is functioning properly, false indicates a problem.
 * @member {Boolean} health
 */
HealthItem.prototype['health'] = undefined;






export default HealthItem;

