/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderItem model module.
 * @module model/OrderItem
 * @version 0.2
 */
class OrderItem {
    /**
     * Constructs a new <code>OrderItem</code>.
     * Represents a purchase order item with complete status and fulfillment information.
     * @alias module:model/OrderItem
     */
    constructor() { 
        
        OrderItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderItem} obj Optional instance to populate.
     * @return {module:model/OrderItem} The populated <code>OrderItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderItem();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = ApiClient.convertToType(data['order_id'], 'Number');
            }
            if (data.hasOwnProperty('order_line_id')) {
                obj['order_line_id'] = ApiClient.convertToType(data['order_line_id'], 'Number');
            }
            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'Number');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = ApiClient.convertToType(data['customer'], 'String');
            }
            if (data.hasOwnProperty('unit_price')) {
                obj['unit_price'] = ApiClient.convertToType(data['unit_price'], 'Number');
            }
            if (data.hasOwnProperty('line_item_price')) {
                obj['line_item_price'] = ApiClient.convertToType(data['line_item_price'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('download_url')) {
                obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
            }
            if (data.hasOwnProperty('view_url')) {
                obj['view_url'] = ApiClient.convertToType(data['view_url'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['customer'] && !(typeof data['customer'] === 'string' || data['customer'] instanceof String)) {
            throw new Error("Expected the field `customer` to be a primitive type in the JSON string but got " + data['customer']);
        }
        // ensure the json data is a string
        if (data['country_code'] && !(typeof data['country_code'] === 'string' || data['country_code'] instanceof String)) {
            throw new Error("Expected the field `country_code` to be a primitive type in the JSON string but got " + data['country_code']);
        }
        // ensure the json data is a string
        if (data['download_url'] && !(typeof data['download_url'] === 'string' || data['download_url'] instanceof String)) {
            throw new Error("Expected the field `download_url` to be a primitive type in the JSON string but got " + data['download_url']);
        }
        // ensure the json data is a string
        if (data['view_url'] && !(typeof data['view_url'] === 'string' || data['view_url'] instanceof String)) {
            throw new Error("Expected the field `view_url` to be a primitive type in the JSON string but got " + data['view_url']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}



/**
 * Vendor order ID that uniquely identifies this purchase order.
 * @member {Number} order_id
 */
OrderItem.prototype['order_id'] = undefined;

/**
 * Line number within the order that identifies this specific item.
 * @member {Number} order_line_id
 */
OrderItem.prototype['order_line_id'] = undefined;

/**
 * Unique identifier for the digital asset associated with this order item.
 * @member {Number} asset_id
 */
OrderItem.prototype['asset_id'] = undefined;

/**
 * Customer name associated with the order for personalization purposes.
 * @member {String} customer
 */
OrderItem.prototype['customer'] = undefined;

/**
 * Unit price for a single item in the vendor's currency.
 * @member {Number} unit_price
 */
OrderItem.prototype['unit_price'] = undefined;

/**
 * Total price for this line item (unit price × quantity) in the vendor's currency.
 * @member {Number} line_item_price
 */
OrderItem.prototype['line_item_price'] = undefined;

/**
 * Quantity of items ordered in this line item.
 * @member {Number} quantity
 */
OrderItem.prototype['quantity'] = undefined;

/**
 * ISO 3166-1 alpha-2 country code for the country of sale.
 * @member {String} country_code
 */
OrderItem.prototype['country_code'] = undefined;

/**
 * Secure download URL for the purchased asset. Available when the order is completed. Null if not yet fulfilled or if not applicable.
 * @member {String} download_url
 */
OrderItem.prototype['download_url'] = undefined;

/**
 * Secure view URL for the purchased asset. Available when the order is completed. Null if not yet fulfilled or if not applicable.
 * @member {String} view_url
 */
OrderItem.prototype['view_url'] = undefined;

/**
 * Current status of the order item (e.g., COMPLETED, PROCESSING, FAILED).
 * @member {String} status
 */
OrderItem.prototype['status'] = undefined;






export default OrderItem;

