/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PackageItem model module.
 * @module model/PackageItem
 * @version 0.2
 */
class PackageItem {
    /**
     * Constructs a new <code>PackageItem</code>.
     * Package deal or bundle that includes an asset.
     * @alias module:model/PackageItem
     */
    constructor() { 
        
        PackageItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PackageItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackageItem} obj Optional instance to populate.
     * @return {module:model/PackageItem} The populated <code>PackageItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackageItem();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'Number');
            }
            if (data.hasOwnProperty('instrumentation_part_code')) {
                obj['instrumentation_part_code'] = ApiClient.convertToType(data['instrumentation_part_code'], 'String');
            }
            if (data.hasOwnProperty('instrumentation_part_name')) {
                obj['instrumentation_part_name'] = ApiClient.convertToType(data['instrumentation_part_name'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('sequence')) {
                obj['sequence'] = ApiClient.convertToType(data['sequence'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PackageItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PackageItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['instrumentation_part_code'] && !(typeof data['instrumentation_part_code'] === 'string' || data['instrumentation_part_code'] instanceof String)) {
            throw new Error("Expected the field `instrumentation_part_code` to be a primitive type in the JSON string but got " + data['instrumentation_part_code']);
        }
        // ensure the json data is a string
        if (data['instrumentation_part_name'] && !(typeof data['instrumentation_part_name'] === 'string' || data['instrumentation_part_name'] instanceof String)) {
            throw new Error("Expected the field `instrumentation_part_name` to be a primitive type in the JSON string but got " + data['instrumentation_part_name']);
        }

        return true;
    }


}



/**
 * Asset ID included in the package.
 * @member {Number} asset_id
 */
PackageItem.prototype['asset_id'] = undefined;

/**
 * Instrumentation part code.
 * @member {String} instrumentation_part_code
 */
PackageItem.prototype['instrumentation_part_code'] = undefined;

/**
 * Instrumentation part name.
 * @member {String} instrumentation_part_name
 */
PackageItem.prototype['instrumentation_part_name'] = undefined;

/**
 * Count of items.
 * @member {Number} count
 */
PackageItem.prototype['count'] = undefined;

/**
 * Sequence number.
 * @member {Number} sequence
 */
PackageItem.prototype['sequence'] = undefined;

/**
 * Score flag indicating if this is a score.
 * @member {Boolean} score
 */
PackageItem.prototype['score'] = undefined;






export default PackageItem;

