/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PriceItem model module.
 * @module model/PriceItem
 * @version 0.2
 */
class PriceItem {
    /**
     * Constructs a new <code>PriceItem</code>.
     * Price information for an asset in different currencies or for different customer segments.
     * @alias module:model/PriceItem
     */
    constructor() { 
        
        PriceItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PriceItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PriceItem} obj Optional instance to populate.
     * @return {module:model/PriceItem} The populated <code>PriceItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PriceItem();

            if (data.hasOwnProperty('type_id')) {
                obj['type_id'] = ApiClient.convertToType(data['type_id'], 'Number');
            }
            if (data.hasOwnProperty('type_usage')) {
                obj['type_usage'] = ApiClient.convertToType(data['type_usage'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PriceItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PriceItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type_usage'] && !(typeof data['type_usage'] === 'string' || data['type_usage'] instanceof String)) {
            throw new Error("Expected the field `type_usage` to be a primitive type in the JSON string but got " + data['type_usage']);
        }

        return true;
    }


}



/**
 * Price type ID.
 * @member {Number} type_id
 */
PriceItem.prototype['type_id'] = undefined;

/**
 * Price type usage (e.g., digital, print).
 * @member {String} type_usage
 */
PriceItem.prototype['type_usage'] = undefined;

/**
 * Price value.
 * @member {Number} price
 */
PriceItem.prototype['price'] = undefined;






export default PriceItem;

