/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PurchaseValidateBeforePaymentRequest model module.
 * @module model/PurchaseValidateBeforePaymentRequest
 * @version 0.2
 */
class PurchaseValidateBeforePaymentRequest {
    /**
     * Constructs a new <code>PurchaseValidateBeforePaymentRequest</code>.
     * Request payload for registering a new purchase transaction. Contains all required information to initiate the purchase of a digital asset.
     * @alias module:model/PurchaseValidateBeforePaymentRequest
     * @param assetId {Number} Unique identifier of the digital asset to be purchased
     * @param customerIp {String} Public IP address of the customer for regional restriction validation
     * @param quantity {Number} The number of asset units to purchase
     */
    constructor(assetId, customerIp, quantity) { 
        
        PurchaseValidateBeforePaymentRequest.initialize(this, assetId, customerIp, quantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId, customerIp, quantity) { 
        obj['asset_id'] = assetId;
        obj['customer_ip'] = customerIp;
        obj['quantity'] = quantity;
    }

    /**
     * Constructs a <code>PurchaseValidateBeforePaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseValidateBeforePaymentRequest} obj Optional instance to populate.
     * @return {module:model/PurchaseValidateBeforePaymentRequest} The populated <code>PurchaseValidateBeforePaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseValidateBeforePaymentRequest();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'Number');
            }
            if (data.hasOwnProperty('customer_ip')) {
                obj['customer_ip'] = ApiClient.convertToType(data['customer_ip'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PurchaseValidateBeforePaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PurchaseValidateBeforePaymentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PurchaseValidateBeforePaymentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['customer_ip'] && !(typeof data['customer_ip'] === 'string' || data['customer_ip'] instanceof String)) {
            throw new Error("Expected the field `customer_ip` to be a primitive type in the JSON string but got " + data['customer_ip']);
        }

        return true;
    }


}

PurchaseValidateBeforePaymentRequest.RequiredProperties = ["asset_id", "customer_ip", "quantity"];

/**
 * Unique identifier of the digital asset to be purchased
 * @member {Number} asset_id
 */
PurchaseValidateBeforePaymentRequest.prototype['asset_id'] = undefined;

/**
 * Public IP address of the customer for regional restriction validation
 * @member {String} customer_ip
 */
PurchaseValidateBeforePaymentRequest.prototype['customer_ip'] = undefined;

/**
 * The number of asset units to purchase
 * @member {Number} quantity
 */
PurchaseValidateBeforePaymentRequest.prototype['quantity'] = undefined;






export default PurchaseValidateBeforePaymentRequest;

