/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetPartForm from './AssetPartForm';

/**
 * The PurchaseRegisterRequest model module.
 * @module model/PurchaseRegisterRequest
 * @version 0.2
 */
class PurchaseRegisterRequest {
    /**
     * Constructs a new <code>PurchaseRegisterRequest</code>.
     * Request payload for registering a new purchase transaction. Contains all required information to initiate the purchase of a digital asset.
     * @alias module:model/PurchaseRegisterRequest
     * @param assetId {Number} Unique identifier for the digital asset to be purchased. This is Hal Leonard's internal asset ID.
     * @param orderNumber {Number} Vendor-generated order number that uniquely identifies this purchase order.
     * @param orderLineId {Number} Line number within the order that identifies this specific item. Used to distinguish multiple items in the same order.
     * @param countryCode {String} ISO 3166-1 alpha-2 country code identifying the country of sale for the customer.
     * @param lineItemPrice {Number} Price for this specific line item as a real number. Represents the total price for the quantity specified.
     * @param unitPrice {Number} Unit price for a single item as a real number
     * @param quantity {Number} Quantity of items being purchased in this line item.
     * @param customer {String} Customer name for asset personalization. May be printed on the asset if personalization is supported.
     */
    constructor(assetId, orderNumber, orderLineId, countryCode, lineItemPrice, unitPrice, quantity, customer) { 
        
        PurchaseRegisterRequest.initialize(this, assetId, orderNumber, orderLineId, countryCode, lineItemPrice, unitPrice, quantity, customer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assetId, orderNumber, orderLineId, countryCode, lineItemPrice, unitPrice, quantity, customer) { 
        obj['asset_id'] = assetId;
        obj['order_number'] = orderNumber;
        obj['order_line_id'] = orderLineId;
        obj['country_code'] = countryCode;
        obj['line_item_price'] = lineItemPrice;
        obj['unit_price'] = unitPrice;
        obj['quantity'] = quantity;
        obj['customer'] = customer;
    }

    /**
     * Constructs a <code>PurchaseRegisterRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PurchaseRegisterRequest} obj Optional instance to populate.
     * @return {module:model/PurchaseRegisterRequest} The populated <code>PurchaseRegisterRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseRegisterRequest();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'Number');
            }
            if (data.hasOwnProperty('order_number')) {
                obj['order_number'] = ApiClient.convertToType(data['order_number'], 'Number');
            }
            if (data.hasOwnProperty('order_line_id')) {
                obj['order_line_id'] = ApiClient.convertToType(data['order_line_id'], 'Number');
            }
            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
            if (data.hasOwnProperty('line_item_price')) {
                obj['line_item_price'] = ApiClient.convertToType(data['line_item_price'], 'Number');
            }
            if (data.hasOwnProperty('unit_price')) {
                obj['unit_price'] = ApiClient.convertToType(data['unit_price'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('customer')) {
                obj['customer'] = ApiClient.convertToType(data['customer'], 'String');
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], [AssetPartForm]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PurchaseRegisterRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PurchaseRegisterRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PurchaseRegisterRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['country_code'] && !(typeof data['country_code'] === 'string' || data['country_code'] instanceof String)) {
            throw new Error("Expected the field `country_code` to be a primitive type in the JSON string but got " + data['country_code']);
        }
        // ensure the json data is a string
        if (data['customer'] && !(typeof data['customer'] === 'string' || data['customer'] instanceof String)) {
            throw new Error("Expected the field `customer` to be a primitive type in the JSON string but got " + data['customer']);
        }
        if (data['parts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parts'])) {
                throw new Error("Expected the field `parts` to be an array in the JSON data but got " + data['parts']);
            }
            // validate the optional field `parts` (array)
            for (const item of data['parts']) {
                AssetPartForm.validateJSON(item);
            };
        }

        return true;
    }


}

PurchaseRegisterRequest.RequiredProperties = ["asset_id", "order_number", "order_line_id", "country_code", "line_item_price", "unit_price", "quantity", "customer"];

/**
 * Unique identifier for the digital asset to be purchased. This is Hal Leonard's internal asset ID.
 * @member {Number} asset_id
 */
PurchaseRegisterRequest.prototype['asset_id'] = undefined;

/**
 * Vendor-generated order number that uniquely identifies this purchase order.
 * @member {Number} order_number
 */
PurchaseRegisterRequest.prototype['order_number'] = undefined;

/**
 * Line number within the order that identifies this specific item. Used to distinguish multiple items in the same order.
 * @member {Number} order_line_id
 */
PurchaseRegisterRequest.prototype['order_line_id'] = undefined;

/**
 * ISO 3166-1 alpha-2 country code identifying the country of sale for the customer.
 * @member {String} country_code
 */
PurchaseRegisterRequest.prototype['country_code'] = undefined;

/**
 * Price for this specific line item as a real number. Represents the total price for the quantity specified.
 * @member {Number} line_item_price
 */
PurchaseRegisterRequest.prototype['line_item_price'] = undefined;

/**
 * Unit price for a single item as a real number
 * @member {Number} unit_price
 */
PurchaseRegisterRequest.prototype['unit_price'] = undefined;

/**
 * Quantity of items being purchased in this line item.
 * @member {Number} quantity
 */
PurchaseRegisterRequest.prototype['quantity'] = undefined;

/**
 * Customer name for asset personalization. May be printed on the asset if personalization is supported.
 * @member {String} customer
 */
PurchaseRegisterRequest.prototype['customer'] = undefined;

/**
 * Optional parts specification for ensemble assets. Allows customers to select specific parts of an ensemble for individual purchase rather than buying the complete set.
 * @member {Array.<module:model/AssetPartForm>} parts
 */
PurchaseRegisterRequest.prototype['parts'] = undefined;






export default PurchaseRegisterRequest;

