/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RelatedGoodItem model module.
 * @module model/RelatedGoodItem
 * @version 0.2
 */
class RelatedGoodItem {
    /**
     * Constructs a new <code>RelatedGoodItem</code>.
     * Related goods (physical products, digital bundles, etc.) associated with an asset.
     * @alias module:model/RelatedGoodItem
     */
    constructor() { 
        
        RelatedGoodItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RelatedGoodItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RelatedGoodItem} obj Optional instance to populate.
     * @return {module:model/RelatedGoodItem} The populated <code>RelatedGoodItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RelatedGoodItem();

            if (data.hasOwnProperty('related_product_id')) {
                obj['related_product_id'] = ApiClient.convertToType(data['related_product_id'], 'Number');
            }
            if (data.hasOwnProperty('group_type_id')) {
                obj['group_type_id'] = ApiClient.convertToType(data['group_type_id'], 'Number');
            }
            if (data.hasOwnProperty('good_type')) {
                obj['good_type'] = ApiClient.convertToType(data['good_type'], 'String');
            }
            if (data.hasOwnProperty('sheet')) {
                obj['sheet'] = ApiClient.convertToType(data['sheet'], 'Boolean');
            }
            if (data.hasOwnProperty('featured')) {
                obj['featured'] = ApiClient.convertToType(data['featured'], 'Boolean');
            }
            if (data.hasOwnProperty('prime_src')) {
                obj['prime_src'] = ApiClient.convertToType(data['prime_src'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RelatedGoodItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RelatedGoodItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['good_type'] && !(typeof data['good_type'] === 'string' || data['good_type'] instanceof String)) {
            throw new Error("Expected the field `good_type` to be a primitive type in the JSON string but got " + data['good_type']);
        }

        return true;
    }


}



/**
 * Related product ID.
 * @member {Number} related_product_id
 */
RelatedGoodItem.prototype['related_product_id'] = undefined;

/**
 * Group type ID.
 * @member {Number} group_type_id
 */
RelatedGoodItem.prototype['group_type_id'] = undefined;

/**
 * Good type (H for hard goods, D for digital, V for virtual).
 * @member {String} good_type
 */
RelatedGoodItem.prototype['good_type'] = undefined;

/**
 * Sheet indicator.
 * @member {Boolean} sheet
 */
RelatedGoodItem.prototype['sheet'] = undefined;

/**
 * Featured indicator.
 * @member {Boolean} featured
 */
RelatedGoodItem.prototype['featured'] = undefined;

/**
 * Prime source indicator.
 * @member {Boolean} prime_src
 */
RelatedGoodItem.prototype['prime_src'] = undefined;






export default RelatedGoodItem;

