/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MedleyAssetItem from './MedleyAssetItem';

/**
 * The UsergenItem model module.
 * @module model/UsergenItem
 * @version 0.2
 */
class UsergenItem {
    /**
     * Constructs a new <code>UsergenItem</code>.
     * User-generated content or customization options associated with an asset.
     * @alias module:model/UsergenItem
     */
    constructor() { 
        
        UsergenItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsergenItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsergenItem} obj Optional instance to populate.
     * @return {module:model/UsergenItem} The populated <code>UsergenItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsergenItem();

            if (data.hasOwnProperty('black_box')) {
                obj['black_box'] = ApiClient.convertToType(data['black_box'], 'Boolean');
            }
            if (data.hasOwnProperty('arrangeable')) {
                obj['arrangeable'] = ApiClient.convertToType(data['arrangeable'], 'Boolean');
            }
            if (data.hasOwnProperty('vendor_product_type')) {
                obj['vendor_product_type'] = ApiClient.convertToType(data['vendor_product_type'], 'String');
            }
            if (data.hasOwnProperty('seller_id')) {
                obj['seller_id'] = ApiClient.convertToType(data['seller_id'], 'Number');
            }
            if (data.hasOwnProperty('authorized_performers')) {
                obj['authorized_performers'] = ApiClient.convertToType(data['authorized_performers'], 'Number');
            }
            if (data.hasOwnProperty('content_provider')) {
                obj['content_provider'] = ApiClient.convertToType(data['content_provider'], 'String');
            }
            if (data.hasOwnProperty('adaptation_product_id')) {
                obj['adaptation_product_id'] = ApiClient.convertToType(data['adaptation_product_id'], 'Number');
            }
            if (data.hasOwnProperty('adaptation_vendor')) {
                obj['adaptation_vendor'] = ApiClient.convertToType(data['adaptation_vendor'], 'String');
            }
            if (data.hasOwnProperty('vendor_song_id')) {
                obj['vendor_song_id'] = ApiClient.convertToType(data['vendor_song_id'], 'String');
            }
            if (data.hasOwnProperty('commission_override_rate')) {
                obj['commission_override_rate'] = ApiClient.convertToType(data['commission_override_rate'], 'Number');
            }
            if (data.hasOwnProperty('publisher_name')) {
                obj['publisher_name'] = ApiClient.convertToType(data['publisher_name'], 'String');
            }
            if (data.hasOwnProperty('medley_assets')) {
                obj['medley_assets'] = ApiClient.convertToType(data['medley_assets'], [MedleyAssetItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsergenItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsergenItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['vendor_product_type'] && !(typeof data['vendor_product_type'] === 'string' || data['vendor_product_type'] instanceof String)) {
            throw new Error("Expected the field `vendor_product_type` to be a primitive type in the JSON string but got " + data['vendor_product_type']);
        }
        // ensure the json data is a string
        if (data['content_provider'] && !(typeof data['content_provider'] === 'string' || data['content_provider'] instanceof String)) {
            throw new Error("Expected the field `content_provider` to be a primitive type in the JSON string but got " + data['content_provider']);
        }
        // ensure the json data is a string
        if (data['adaptation_vendor'] && !(typeof data['adaptation_vendor'] === 'string' || data['adaptation_vendor'] instanceof String)) {
            throw new Error("Expected the field `adaptation_vendor` to be a primitive type in the JSON string but got " + data['adaptation_vendor']);
        }
        // ensure the json data is a string
        if (data['vendor_song_id'] && !(typeof data['vendor_song_id'] === 'string' || data['vendor_song_id'] instanceof String)) {
            throw new Error("Expected the field `vendor_song_id` to be a primitive type in the JSON string but got " + data['vendor_song_id']);
        }
        // ensure the json data is a string
        if (data['publisher_name'] && !(typeof data['publisher_name'] === 'string' || data['publisher_name'] instanceof String)) {
            throw new Error("Expected the field `publisher_name` to be a primitive type in the JSON string but got " + data['publisher_name']);
        }
        if (data['medley_assets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['medley_assets'])) {
                throw new Error("Expected the field `medley_assets` to be an array in the JSON data but got " + data['medley_assets']);
            }
            // validate the optional field `medley_assets` (array)
            for (const item of data['medley_assets']) {
                MedleyAssetItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Black box flag indicating if the asset is a black box item.
 * @member {Boolean} black_box
 */
UsergenItem.prototype['black_box'] = undefined;

/**
 * Arrangeable flag indicating if the asset can be arranged.
 * @member {Boolean} arrangeable
 */
UsergenItem.prototype['arrangeable'] = undefined;

/**
 * Vendor product type identifier.
 * @member {String} vendor_product_type
 */
UsergenItem.prototype['vendor_product_type'] = undefined;

/**
 * Seller ID for the user-generated content.
 * @member {Number} seller_id
 */
UsergenItem.prototype['seller_id'] = undefined;

/**
 * Number of authorized performers for the content.
 * @member {Number} authorized_performers
 */
UsergenItem.prototype['authorized_performers'] = undefined;

/**
 * Content provider name.
 * @member {String} content_provider
 */
UsergenItem.prototype['content_provider'] = undefined;

/**
 * Adaptation product ID.
 * @member {Number} adaptation_product_id
 */
UsergenItem.prototype['adaptation_product_id'] = undefined;

/**
 * Adaptation vendor name.
 * @member {String} adaptation_vendor
 */
UsergenItem.prototype['adaptation_vendor'] = undefined;

/**
 * Vendor song ID.
 * @member {String} vendor_song_id
 */
UsergenItem.prototype['vendor_song_id'] = undefined;

/**
 * Commission override rate as a decimal.
 * @member {Number} commission_override_rate
 */
UsergenItem.prototype['commission_override_rate'] = undefined;

/**
 * Publisher name.
 * @member {String} publisher_name
 */
UsergenItem.prototype['publisher_name'] = undefined;

/**
 * List of medley assets included in this user-generated content.
 * @member {Array.<module:model/MedleyAssetItem>} medley_assets
 */
UsergenItem.prototype['medley_assets'] = undefined;






export default UsergenItem;

