/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidationToken model module.
 * @module model/ValidationToken
 * @version 0.2
 */
class ValidationToken {
    /**
     * Constructs a new <code>ValidationToken</code>.
     * Successful validation response containing a temporary token to proceed with the payment.
     * @alias module:model/ValidationToken
     * @param token {String} Validation token
     * @param expDate {Number} Expiration date in UNIX timestamp format
     */
    constructor(token, expDate) { 
        
        ValidationToken.initialize(this, token, expDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token, expDate) { 
        obj['token'] = token;
        obj['exp_date'] = expDate;
    }

    /**
     * Constructs a <code>ValidationToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidationToken} obj Optional instance to populate.
     * @return {module:model/ValidationToken} The populated <code>ValidationToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationToken();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('exp_date')) {
                obj['exp_date'] = ApiClient.convertToType(data['exp_date'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidationToken</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidationToken</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ValidationToken.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}

ValidationToken.RequiredProperties = ["token", "exp_date"];

/**
 * Validation token
 * @member {String} token
 */
ValidationToken.prototype['token'] = undefined;

/**
 * Expiration date in UNIX timestamp format
 * @member {Number} exp_date
 */
ValidationToken.prototype['exp_date'] = undefined;






export default ValidationToken;

