/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AssetsListResponse from '../model/AssetsListResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* Assets service.
* @module api/AssetsApi
* @version 0.2
*/
export default class AssetsApi {

    /**
    * Constructs a new AssetsApi. 
    * @alias module:api/AssetsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the assetsList operation.
     * @callback module:api/AssetsApi~assetsListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AssetsListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a paginated list of digital assets
     * Returns a list of digital assets with their complete metadata. Assets include information about formats, pricing, contributors, categories, instruments, and related media.
     * @param {Object} opts Optional parameters
     * @param {Number} [pageSize = 20)] Number of assets to return per page
     * @param {Number} [lastId] The ID of the last asset from the previous page. Used for pagination to retrieve the next page of results.
     * @param {module:api/AssetsApi~assetsListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AssetsListResponse}
     */
    assetsList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page_size': opts['pageSize'],
        'last_id': opts['lastId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AssetsListResponse;
      return this.apiClient.callApi(
        '/assets/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
