/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import HealthItem from '../model/HealthItem';

/**
* Health service.
* @module api/HealthApi
* @version 0.2
*/
export default class HealthApi {

    /**
    * Constructs a new HealthApi. 
    * @alias module:api/HealthApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the health operation.
     * @callback module:api/HealthApi~healthCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/HealthItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Perform system health check
     * Checks the status of critical system components such as database connections and external services. Returns an array of health check results indicating whether each component is functioning properly. This endpoint is publicly accessible and can be used for monitoring system uptime.
     * @param {module:api/HealthApi~healthCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/HealthItem>}
     */
    health(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [HealthItem];
      return this.apiClient.callApi(
        '/health', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
