/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';

/**
* PurchaseCancel service.
* @module api/PurchaseCancelApi
* @version 0.2
*/
export default class PurchaseCancelApi {

    /**
    * Constructs a new PurchaseCancelApi. 
    * @alias module:api/PurchaseCancelApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseCancel operation.
     * @callback module:api/PurchaseCancelApi~connectorPurchaseCancelCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel purchase order line item
     * Cancels a specific line item within a purchase order. The order must be in a cancellable status. Both order ID and order line ID must be specified.
     * @param {Number} orderId Vendor order ID containing the line item to cancel
     * @param {Number} orderLineId Specific line item within the order to cancel
     * @param {module:api/PurchaseCancelApi~connectorPurchaseCancelCallback} callback The callback function, accepting three arguments: error, data, response
     */
    connectorPurchaseCancel(orderId, orderLineId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseCancel");
      }
      // verify the required parameter 'orderLineId' is set
      if (orderLineId === undefined || orderLineId === null) {
        throw new Error("Missing the required parameter 'orderLineId' when calling connectorPurchaseCancel");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId,
        'order_line_id': orderLineId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/purchase/cancel', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
