/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DownloadUrl from '../model/DownloadUrl';
import ErrorResponse from '../model/ErrorResponse';
import OrderItem from '../model/OrderItem';
import OrderProcessingFailedResponse from '../model/OrderProcessingFailedResponse';
import PurchaseInProcessingResponse from '../model/PurchaseInProcessingResponse';
import PurchaseRegisterRequest from '../model/PurchaseRegisterRequest';
import PurchaseValidateBeforePaymentRequest from '../model/PurchaseValidateBeforePaymentRequest';
import ValidationToken from '../model/ValidationToken';
import ViewUrl from '../model/ViewUrl';

/**
* Purchase service.
* @module api/PurchaseApi
* @version 0.2
*/
export default class PurchaseApi {

    /**
    * Constructs a new PurchaseApi. 
    * @alias module:api/PurchaseApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseCancel operation.
     * @callback module:api/PurchaseApi~connectorPurchaseCancelCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel purchase order line item
     * Cancels a specific line item within a purchase order. The order must be in a cancellable status. Both order ID and order line ID must be specified.
     * @param {Number} orderId Vendor order ID containing the line item to cancel
     * @param {Number} orderLineId Specific line item within the order to cancel
     * @param {module:api/PurchaseApi~connectorPurchaseCancelCallback} callback The callback function, accepting three arguments: error, data, response
     */
    connectorPurchaseCancel(orderId, orderLineId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseCancel");
      }
      // verify the required parameter 'orderLineId' is set
      if (orderLineId === undefined || orderLineId === null) {
        throw new Error("Missing the required parameter 'orderLineId' when calling connectorPurchaseCancel");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId,
        'order_line_id': orderLineId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/purchase/cancel', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the connectorPurchaseDownloadUrl operation.
     * @callback module:api/PurchaseApi~connectorPurchaseDownloadUrlCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DownloadUrl} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get asset download URL
     * Generates and returns a secure download URL for a purchased digital asset. The URL can be used to download the asset file.
     * @param {Number} orderId Vendor order ID that contains the asset to download
     * @param {Number} orderLineId Specific line item within the order that identifies the asset to download
     * @param {module:api/PurchaseApi~connectorPurchaseDownloadUrlCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DownloadUrl}
     */
    connectorPurchaseDownloadUrl(orderId, orderLineId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseDownloadUrl");
      }
      // verify the required parameter 'orderLineId' is set
      if (orderLineId === undefined || orderLineId === null) {
        throw new Error("Missing the required parameter 'orderLineId' when calling connectorPurchaseDownloadUrl");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId,
        'order_line_id': orderLineId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DownloadUrl;
      return this.apiClient.callApi(
        '/purchase/download-url', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the connectorPurchaseInfo operation.
     * @callback module:api/PurchaseApi~connectorPurchaseInfoCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/OrderItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve purchase order information
     * Returns detailed information about a purchase order including status, asset details, pricing, and fulfillment status. Response varies based on processing status (complete, processing, failed).
     * @param {Number} orderId Vendor order ID to retrieve purchase details for. This is the unique identifier assigned by the vendor when placing the order.
     * @param {module:api/PurchaseApi~connectorPurchaseInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/OrderItem>}
     */
    connectorPurchaseInfo(orderId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseInfo");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [OrderItem];
      return this.apiClient.callApi(
        '/purchase/info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the connectorPurchaseRegister operation.
     * @callback module:api/PurchaseApi~connectorPurchaseRegisterCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register a new purchase transaction
     * Initiates the purchase process for a digital asset. Validates request parameters, creates a new order, and begins fulfillment. This is an asynchronous operation - use /purchase/info to check order status.
     * @param {module:model/PurchaseRegisterRequest} purchaseRegisterRequest Purchase registration request with asset and order details
     * @param {module:api/PurchaseApi~connectorPurchaseRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     */
    connectorPurchaseRegister(purchaseRegisterRequest, callback) {
      let postBody = purchaseRegisterRequest;
      // verify the required parameter 'purchaseRegisterRequest' is set
      if (purchaseRegisterRequest === undefined || purchaseRegisterRequest === null) {
        throw new Error("Missing the required parameter 'purchaseRegisterRequest' when calling connectorPurchaseRegister");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/purchase/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the connectorPurchaseValidatePurchaseBeforePayment operation.
     * @callback module:api/PurchaseApi~connectorPurchaseValidatePurchaseBeforePaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ValidationToken} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Validate purchase before payment
     * Validates purchase parameters before payment is initiated. Checks asset availability, regional restrictions (based on buyer IP), and minimum quantity requirements. 
     * @param {module:model/PurchaseValidateBeforePaymentRequest} purchaseValidateBeforePaymentRequest Purchase validation request with asset, buyer IP and quantity
     * @param {module:api/PurchaseApi~connectorPurchaseValidatePurchaseBeforePaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ValidationToken}
     */
    connectorPurchaseValidatePurchaseBeforePayment(purchaseValidateBeforePaymentRequest, callback) {
      let postBody = purchaseValidateBeforePaymentRequest;
      // verify the required parameter 'purchaseValidateBeforePaymentRequest' is set
      if (purchaseValidateBeforePaymentRequest === undefined || purchaseValidateBeforePaymentRequest === null) {
        throw new Error("Missing the required parameter 'purchaseValidateBeforePaymentRequest' when calling connectorPurchaseValidatePurchaseBeforePayment");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ValidationToken;
      return this.apiClient.callApi(
        '/purchase/validate-purchase-before-payment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the connectorPurchaseViewUrl operation.
     * @callback module:api/PurchaseApi~connectorPurchaseViewUrlCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ViewUrl} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get asset view URL
     * Generates and returns a secure, time-limited view URL for a purchased digital asset. The URL can be used to view the asset online (e.g., sheet music viewer).
     * @param {Number} orderId Vendor order ID that contains the asset to view
     * @param {Number} orderLineId Specific line item within the order that identifies the asset to view
     * @param {module:api/PurchaseApi~connectorPurchaseViewUrlCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ViewUrl}
     */
    connectorPurchaseViewUrl(orderId, orderLineId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseViewUrl");
      }
      // verify the required parameter 'orderLineId' is set
      if (orderLineId === undefined || orderLineId === null) {
        throw new Error("Missing the required parameter 'orderLineId' when calling connectorPurchaseViewUrl");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId,
        'order_line_id': orderLineId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ViewUrl;
      return this.apiClient.callApi(
        '/purchase/view-url', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
