/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import ViewUrl from '../model/ViewUrl';

/**
* PurchaseViewUrl service.
* @module api/PurchaseViewUrlApi
* @version 0.2
*/
export default class PurchaseViewUrlApi {

    /**
    * Constructs a new PurchaseViewUrlApi. 
    * @alias module:api/PurchaseViewUrlApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseViewUrl operation.
     * @callback module:api/PurchaseViewUrlApi~connectorPurchaseViewUrlCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ViewUrl} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get asset view URL
     * Generates and returns a secure, time-limited view URL for a purchased digital asset. The URL can be used to view the asset online (e.g., sheet music viewer).
     * @param {Number} orderId Vendor order ID that contains the asset to view
     * @param {Number} orderLineId Specific line item within the order that identifies the asset to view
     * @param {module:api/PurchaseViewUrlApi~connectorPurchaseViewUrlCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ViewUrl}
     */
    connectorPurchaseViewUrl(orderId, orderLineId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseViewUrl");
      }
      // verify the required parameter 'orderLineId' is set
      if (orderLineId === undefined || orderLineId === null) {
        throw new Error("Missing the required parameter 'orderLineId' when calling connectorPurchaseViewUrl");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId,
        'order_line_id': orderLineId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ViewUrl;
      return this.apiClient.callApi(
        '/purchase/view-url', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
