/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import OrderItem from '../model/OrderItem';
import OrderProcessingFailedResponse from '../model/OrderProcessingFailedResponse';
import PurchaseInProcessingResponse from '../model/PurchaseInProcessingResponse';

/**
* PurchaseInfo service.
* @module api/PurchaseInfoApi
* @version 0.2
*/
export default class PurchaseInfoApi {

    /**
    * Constructs a new PurchaseInfoApi. 
    * @alias module:api/PurchaseInfoApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseInfo operation.
     * @callback module:api/PurchaseInfoApi~connectorPurchaseInfoCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/OrderItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve purchase order information
     * Returns detailed information about a purchase order including status, asset details, pricing, and fulfillment status. Response varies based on processing status (complete, processing, failed).
     * @param {Number} orderId Vendor order ID to retrieve purchase details for. This is the unique identifier assigned by the vendor when placing the order.
     * @param {module:api/PurchaseInfoApi~connectorPurchaseInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/OrderItem>}
     */
    connectorPurchaseInfo(orderId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseInfo");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [OrderItem];
      return this.apiClient.callApi(
        '/purchase/info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
