/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DownloadUrl from '../model/DownloadUrl';
import ErrorResponse from '../model/ErrorResponse';

/**
* PurchaseDownloadUrl service.
* @module api/PurchaseDownloadUrlApi
* @version 0.2
*/
export default class PurchaseDownloadUrlApi {

    /**
    * Constructs a new PurchaseDownloadUrlApi. 
    * @alias module:api/PurchaseDownloadUrlApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseDownloadUrl operation.
     * @callback module:api/PurchaseDownloadUrlApi~connectorPurchaseDownloadUrlCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DownloadUrl} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get asset download URL
     * Generates and returns a secure download URL for a purchased digital asset. The URL can be used to download the asset file.
     * @param {Number} orderId Vendor order ID that contains the asset to download
     * @param {Number} orderLineId Specific line item within the order that identifies the asset to download
     * @param {module:api/PurchaseDownloadUrlApi~connectorPurchaseDownloadUrlCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DownloadUrl}
     */
    connectorPurchaseDownloadUrl(orderId, orderLineId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling connectorPurchaseDownloadUrl");
      }
      // verify the required parameter 'orderLineId' is set
      if (orderLineId === undefined || orderLineId === null) {
        throw new Error("Missing the required parameter 'orderLineId' when calling connectorPurchaseDownloadUrl");
      }

      let pathParams = {
      };
      let queryParams = {
        'order_id': orderId,
        'order_line_id': orderLineId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DownloadUrl;
      return this.apiClient.callApi(
        '/purchase/download-url', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
