/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import PurchaseRegisterRequest from '../model/PurchaseRegisterRequest';

/**
* PurchaseRegister service.
* @module api/PurchaseRegisterApi
* @version 0.2
*/
export default class PurchaseRegisterApi {

    /**
    * Constructs a new PurchaseRegisterApi. 
    * @alias module:api/PurchaseRegisterApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseRegister operation.
     * @callback module:api/PurchaseRegisterApi~connectorPurchaseRegisterCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register a new purchase transaction
     * Initiates the purchase process for a digital asset. Validates request parameters, creates a new order, and begins fulfillment. This is an asynchronous operation - use /purchase/info to check order status.
     * @param {module:model/PurchaseRegisterRequest} purchaseRegisterRequest Purchase registration request with asset and order details
     * @param {module:api/PurchaseRegisterApi~connectorPurchaseRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     */
    connectorPurchaseRegister(purchaseRegisterRequest, callback) {
      let postBody = purchaseRegisterRequest;
      // verify the required parameter 'purchaseRegisterRequest' is set
      if (purchaseRegisterRequest === undefined || purchaseRegisterRequest === null) {
        throw new Error("Missing the required parameter 'purchaseRegisterRequest' when calling connectorPurchaseRegister");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/purchase/register', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
