/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import PurchaseValidateBeforePaymentRequest from '../model/PurchaseValidateBeforePaymentRequest';
import ValidationToken from '../model/ValidationToken';

/**
* PurchaseValidation service.
* @module api/PurchaseValidationApi
* @version 0.2
*/
export default class PurchaseValidationApi {

    /**
    * Constructs a new PurchaseValidationApi. 
    * @alias module:api/PurchaseValidationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the connectorPurchaseValidatePurchaseBeforePayment operation.
     * @callback module:api/PurchaseValidationApi~connectorPurchaseValidatePurchaseBeforePaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ValidationToken} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Validate purchase before payment
     * Validates purchase parameters before payment is initiated. Checks asset availability, regional restrictions (based on buyer IP), and minimum quantity requirements. 
     * @param {module:model/PurchaseValidateBeforePaymentRequest} purchaseValidateBeforePaymentRequest Purchase validation request with asset, buyer IP and quantity
     * @param {module:api/PurchaseValidationApi~connectorPurchaseValidatePurchaseBeforePaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ValidationToken}
     */
    connectorPurchaseValidatePurchaseBeforePayment(purchaseValidateBeforePaymentRequest, callback) {
      let postBody = purchaseValidateBeforePaymentRequest;
      // verify the required parameter 'purchaseValidateBeforePaymentRequest' is set
      if (purchaseValidateBeforePaymentRequest === undefined || purchaseValidateBeforePaymentRequest === null) {
        throw new Error("Missing the required parameter 'purchaseValidateBeforePaymentRequest' when calling connectorPurchaseValidatePurchaseBeforePayment");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['access_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ValidationToken;
      return this.apiClient.callApi(
        '/purchase/validate-purchase-before-payment', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
