/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HlConnector);
  }
}(this, function(expect, HlConnector) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HlConnector.AssetItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssetItem', function() {
    it('should create an instance of AssetItem', function() {
      // uncomment below and update the code to test AssetItem
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be.a(HlConnector.AssetItem);
    });

    it('should have the property assetId (base name: "asset_id")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property formatShortName (base name: "format_short_name")', function() {
      // uncomment below and update the code to test the property formatShortName
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property format (base name: "format")', function() {
      // uncomment below and update the code to test the property format
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property pageCount (base name: "page_count")', function() {
      // uncomment below and update the code to test the property pageCount
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property songNumber (base name: "song_number")', function() {
      // uncomment below and update the code to test the property songNumber
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property publicDomain (base name: "public_domain")', function() {
      // uncomment below and update the code to test the property publicDomain
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property externalRef (base name: "external_ref")', function() {
      // uncomment below and update the code to test the property externalRef
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property externalRefId (base name: "external_ref_id")', function() {
      // uncomment below and update the code to test the property externalRefId
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property voicing (base name: "voicing")', function() {
      // uncomment below and update the code to test the property voicing
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property performanceTime (base name: "performance_time")', function() {
      // uncomment below and update the code to test the property performanceTime
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property difficultyLevelLow (base name: "difficulty_level_low")', function() {
      // uncomment below and update the code to test the property difficultyLevelLow
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property difficultyLevelHigh (base name: "difficulty_level_high")', function() {
      // uncomment below and update the code to test the property difficultyLevelHigh
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property minQty (base name: "min_qty")', function() {
      // uncomment below and update the code to test the property minQty
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property tempo (base name: "tempo")', function() {
      // uncomment below and update the code to test the property tempo
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property world (base name: "world")', function() {
      // uncomment below and update the code to test the property world
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property retailPrice (base name: "retail_price")', function() {
      // uncomment below and update the code to test the property retailPrice
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property smdId (base name: "smd_id")', function() {
      // uncomment below and update the code to test the property smdId
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property assetType (base name: "asset_type")', function() {
      // uncomment below and update the code to test the property assetType
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property explicit (base name: "explicit")', function() {
      // uncomment below and update the code to test the property explicit
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property partable (base name: "partable")', function() {
      // uncomment below and update the code to test the property partable
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property countries (base name: "countries")', function() {
      // uncomment below and update the code to test the property countries
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property instruments (base name: "instruments")', function() {
      // uncomment below and update the code to test the property instruments
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property contributors (base name: "contributors")', function() {
      // uncomment below and update the code to test the property contributors
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property keywords (base name: "keywords")', function() {
      // uncomment below and update the code to test the property keywords
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property relatedGoods (base name: "related_goods")', function() {
      // uncomment below and update the code to test the property relatedGoods
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property renderings (base name: "renderings")', function() {
      // uncomment below and update the code to test the property renderings
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property series (base name: "series")', function() {
      // uncomment below and update the code to test the property series
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property skills (base name: "skills")', function() {
      // uncomment below and update the code to test the property skills
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property usergens (base name: "usergens")', function() {
      // uncomment below and update the code to test the property usergens
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property prices (base name: "prices")', function() {
      // uncomment below and update the code to test the property prices
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

    it('should have the property packages (base name: "packages")', function() {
      // uncomment below and update the code to test the property packages
      //var instance = new HlConnector.AssetItem();
      //expect(instance).to.be();
    });

  });

}));
