/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HlConnect);
  }
}(this, function(expect, HlConnect) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HlConnect.PurchaseValidateBeforePaymentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PurchaseValidateBeforePaymentRequest', function() {
    it('should create an instance of PurchaseValidateBeforePaymentRequest', function() {
      // uncomment below and update the code to test PurchaseValidateBeforePaymentRequest
      //var instance = new HlConnect.PurchaseValidateBeforePaymentRequest();
      //expect(instance).to.be.a(HlConnect.PurchaseValidateBeforePaymentRequest);
    });

    it('should have the property assetId (base name: "asset_id")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new HlConnect.PurchaseValidateBeforePaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property customerIp (base name: "customer_ip")', function() {
      // uncomment below and update the code to test the property customerIp
      //var instance = new HlConnect.PurchaseValidateBeforePaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instance = new HlConnect.PurchaseValidateBeforePaymentRequest();
      //expect(instance).to.be();
    });

  });

}));
