/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HlConnector);
  }
}(this, function(expect, HlConnector) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HlConnector.RelatedGoodItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RelatedGoodItem', function() {
    it('should create an instance of RelatedGoodItem', function() {
      // uncomment below and update the code to test RelatedGoodItem
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be.a(HlConnector.RelatedGoodItem);
    });

    it('should have the property relatedProductId (base name: "related_product_id")', function() {
      // uncomment below and update the code to test the property relatedProductId
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be();
    });

    it('should have the property groupTypeId (base name: "group_type_id")', function() {
      // uncomment below and update the code to test the property groupTypeId
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be();
    });

    it('should have the property goodType (base name: "good_type")', function() {
      // uncomment below and update the code to test the property goodType
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be();
    });

    it('should have the property sheet (base name: "sheet")', function() {
      // uncomment below and update the code to test the property sheet
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be();
    });

    it('should have the property featured (base name: "featured")', function() {
      // uncomment below and update the code to test the property featured
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be();
    });

    it('should have the property primeSrc (base name: "prime_src")', function() {
      // uncomment below and update the code to test the property primeSrc
      //var instance = new HlConnector.RelatedGoodItem();
      //expect(instance).to.be();
    });

  });

}));
