/**
 * HL Connector
 * HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HlConnector);
  }
}(this, function(expect, HlConnector) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HlConnector.UsergenItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsergenItem', function() {
    it('should create an instance of UsergenItem', function() {
      // uncomment below and update the code to test UsergenItem
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be.a(HlConnector.UsergenItem);
    });

    it('should have the property blackBox (base name: "black_box")', function() {
      // uncomment below and update the code to test the property blackBox
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property arrangeable (base name: "arrangeable")', function() {
      // uncomment below and update the code to test the property arrangeable
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property vendorProductType (base name: "vendor_product_type")', function() {
      // uncomment below and update the code to test the property vendorProductType
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property sellerId (base name: "seller_id")', function() {
      // uncomment below and update the code to test the property sellerId
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property authorizedPerformers (base name: "authorized_performers")', function() {
      // uncomment below and update the code to test the property authorizedPerformers
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property contentProvider (base name: "content_provider")', function() {
      // uncomment below and update the code to test the property contentProvider
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property adaptationProductId (base name: "adaptation_product_id")', function() {
      // uncomment below and update the code to test the property adaptationProductId
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property adaptationVendor (base name: "adaptation_vendor")', function() {
      // uncomment below and update the code to test the property adaptationVendor
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property vendorSongId (base name: "vendor_song_id")', function() {
      // uncomment below and update the code to test the property vendorSongId
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property commissionOverrideRate (base name: "commission_override_rate")', function() {
      // uncomment below and update the code to test the property commissionOverrideRate
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property publisherName (base name: "publisher_name")', function() {
      // uncomment below and update the code to test the property publisherName
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

    it('should have the property medleyAssets (base name: "medley_assets")', function() {
      // uncomment below and update the code to test the property medleyAssets
      //var instance = new HlConnector.UsergenItem();
      //expect(instance).to.be();
    });

  });

}));
