/**
 * HL Connect
 * HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AssetItem from './model/AssetItem';
import AssetPartForm from './model/AssetPartForm';
import AssetsListResponse from './model/AssetsListResponse';
import ContributorItem from './model/ContributorItem';
import DownloadUrl from './model/DownloadUrl';
import ErrorResponse from './model/ErrorResponse';
import HealthItem from './model/HealthItem';
import ImageItem from './model/ImageItem';
import InstrumentItem from './model/InstrumentItem';
import MedleyAssetItem from './model/MedleyAssetItem';
import OrderItem from './model/OrderItem';
import OrderProcessingFailedResponse from './model/OrderProcessingFailedResponse';
import PackageItem from './model/PackageItem';
import PriceItem from './model/PriceItem';
import PurchaseInProcessingResponse from './model/PurchaseInProcessingResponse';
import PurchaseRegisterRequest from './model/PurchaseRegisterRequest';
import PurchaseValidateBeforePaymentRequest from './model/PurchaseValidateBeforePaymentRequest';
import RelatedGoodItem from './model/RelatedGoodItem';
import RenderingItem from './model/RenderingItem';
import UsergenItem from './model/UsergenItem';
import ValidationToken from './model/ValidationToken';
import ViewUrl from './model/ViewUrl';
import AssetsApi from './api/AssetsApi';
import HealthApi from './api/HealthApi';
import PurchaseApi from './api/PurchaseApi';
import PurchaseCancelApi from './api/PurchaseCancelApi';
import PurchaseDownloadUrlApi from './api/PurchaseDownloadUrlApi';
import PurchaseInfoApi from './api/PurchaseInfoApi';
import PurchaseRegisterApi from './api/PurchaseRegisterApi';
import PurchaseValidationApi from './api/PurchaseValidationApi';
import PurchaseViewUrlApi from './api/PurchaseViewUrlApi';


/**
* HL Connect provides a simplified API interface to Hal Leonard&#39;s Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard&#39;s digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HlConnect = require('index'); // See note below*.
* var xxxSvc = new HlConnect.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HlConnect.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HlConnect.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HlConnect.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AssetItem model constructor.
     * @property {module:model/AssetItem}
     */
    AssetItem,

    /**
     * The AssetPartForm model constructor.
     * @property {module:model/AssetPartForm}
     */
    AssetPartForm,

    /**
     * The AssetsListResponse model constructor.
     * @property {module:model/AssetsListResponse}
     */
    AssetsListResponse,

    /**
     * The ContributorItem model constructor.
     * @property {module:model/ContributorItem}
     */
    ContributorItem,

    /**
     * The DownloadUrl model constructor.
     * @property {module:model/DownloadUrl}
     */
    DownloadUrl,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The HealthItem model constructor.
     * @property {module:model/HealthItem}
     */
    HealthItem,

    /**
     * The ImageItem model constructor.
     * @property {module:model/ImageItem}
     */
    ImageItem,

    /**
     * The InstrumentItem model constructor.
     * @property {module:model/InstrumentItem}
     */
    InstrumentItem,

    /**
     * The MedleyAssetItem model constructor.
     * @property {module:model/MedleyAssetItem}
     */
    MedleyAssetItem,

    /**
     * The OrderItem model constructor.
     * @property {module:model/OrderItem}
     */
    OrderItem,

    /**
     * The OrderProcessingFailedResponse model constructor.
     * @property {module:model/OrderProcessingFailedResponse}
     */
    OrderProcessingFailedResponse,

    /**
     * The PackageItem model constructor.
     * @property {module:model/PackageItem}
     */
    PackageItem,

    /**
     * The PriceItem model constructor.
     * @property {module:model/PriceItem}
     */
    PriceItem,

    /**
     * The PurchaseInProcessingResponse model constructor.
     * @property {module:model/PurchaseInProcessingResponse}
     */
    PurchaseInProcessingResponse,

    /**
     * The PurchaseRegisterRequest model constructor.
     * @property {module:model/PurchaseRegisterRequest}
     */
    PurchaseRegisterRequest,

    /**
     * The PurchaseValidateBeforePaymentRequest model constructor.
     * @property {module:model/PurchaseValidateBeforePaymentRequest}
     */
    PurchaseValidateBeforePaymentRequest,

    /**
     * The RelatedGoodItem model constructor.
     * @property {module:model/RelatedGoodItem}
     */
    RelatedGoodItem,

    /**
     * The RenderingItem model constructor.
     * @property {module:model/RenderingItem}
     */
    RenderingItem,

    /**
     * The UsergenItem model constructor.
     * @property {module:model/UsergenItem}
     */
    UsergenItem,

    /**
     * The ValidationToken model constructor.
     * @property {module:model/ValidationToken}
     */
    ValidationToken,

    /**
     * The ViewUrl model constructor.
     * @property {module:model/ViewUrl}
     */
    ViewUrl,

    /**
    * The AssetsApi service constructor.
    * @property {module:api/AssetsApi}
    */
    AssetsApi,

    /**
    * The HealthApi service constructor.
    * @property {module:api/HealthApi}
    */
    HealthApi,

    /**
    * The PurchaseApi service constructor.
    * @property {module:api/PurchaseApi}
    */
    PurchaseApi,

    /**
    * The PurchaseCancelApi service constructor.
    * @property {module:api/PurchaseCancelApi}
    */
    PurchaseCancelApi,

    /**
    * The PurchaseDownloadUrlApi service constructor.
    * @property {module:api/PurchaseDownloadUrlApi}
    */
    PurchaseDownloadUrlApi,

    /**
    * The PurchaseInfoApi service constructor.
    * @property {module:api/PurchaseInfoApi}
    */
    PurchaseInfoApi,

    /**
    * The PurchaseRegisterApi service constructor.
    * @property {module:api/PurchaseRegisterApi}
    */
    PurchaseRegisterApi,

    /**
    * The PurchaseValidationApi service constructor.
    * @property {module:api/PurchaseValidationApi}
    */
    PurchaseValidationApi,

    /**
    * The PurchaseViewUrlApi service constructor.
    * @property {module:api/PurchaseViewUrlApi}
    */
    PurchaseViewUrlApi
};
